from app.schemas import Instrument, InstrumentStatus, InstrumentType


INSTRUMENTS = [
    Instrument(
        id='flow-drgm-1600-001',
        type=InstrumentType.FLOWMETER,
        name='ДРГ.М-1600',
        manufacturer='МКАИР',
        model='ДРГ.М-1600',
        serial_number='DRG1600-001',
        status=InstrumentStatus.AVAILABLE,
        range_min=40,
        range_max=1600,
        range_unit='m3/h',
        dn_mm=100,
        error_percent=1.5,
        certificate_number='ПВ-F-001',
        calibration_due='2027-04-22',
        location='Склад КИП',
        warehouse_bin='F-01',
        notes='Базовый расходомер для альфа-сценариев ДРГ.',
    ),
    Instrument(
        id='flow-drgm-2500-001',
        type=InstrumentType.FLOWMETER,
        name='ДРГ.М-2500',
        manufacturer='МКАИР',
        model='ДРГ.М-2500',
        serial_number='DRG2500-001',
        status=InstrumentStatus.AVAILABLE,
        range_min=62.5,
        range_max=2500,
        range_unit='m3/h',
        dn_mm=150,
        error_percent=1.2,
        certificate_number='ПВ-F-002',
        calibration_due='2027-05-12',
        location='Склад КИП',
        warehouse_bin='F-02',
    ),
    Instrument(
        id='flow-drgm-160-001',
        type=InstrumentType.FLOWMETER,
        name='DRG.M-160 DN80',
        manufacturer='MKAIR',
        model='DRG.M-160',
        serial_number='DRG160-001',
        status=InstrumentStatus.AVAILABLE,
        range_min=4,
        range_max=160,
        range_unit='m3/h',
        dn_mm=80,
        error_percent=1.5,
        certificate_number='PV-F-160',
        calibration_due='2027-04-22',
        location='KIP warehouse',
        warehouse_bin='F-03',
    ),
    Instrument(
        id='flow-drgm-400-001',
        type=InstrumentType.FLOWMETER,
        name='DRG.M-400 DN100',
        manufacturer='MKAIR',
        model='DRG.M-400',
        serial_number='DRG400-001',
        status=InstrumentStatus.AVAILABLE,
        range_min=10,
        range_max=400,
        range_unit='m3/h',
        dn_mm=100,
        error_percent=1.5,
        certificate_number='PV-F-400',
        calibration_due='2027-04-22',
        location='KIP warehouse',
        warehouse_bin='F-04',
    ),
    Instrument(
        id='flow-drgm-800-001',
        type=InstrumentType.FLOWMETER,
        name='DRG.M-800 DN100',
        manufacturer='MKAIR',
        model='DRG.M-800',
        serial_number='DRG800-001',
        status=InstrumentStatus.AVAILABLE,
        range_min=20,
        range_max=800,
        range_unit='m3/h',
        dn_mm=100,
        error_percent=1.5,
        certificate_number='PV-F-800',
        calibration_due='2027-04-22',
        location='KIP warehouse',
        warehouse_bin='F-05',
    ),
    Instrument(
        id='flow-drgm-5000-001',
        type=InstrumentType.FLOWMETER,
        name='DRG.M-5000 DN150',
        manufacturer='MKAIR',
        model='DRG.M-5000',
        serial_number='DRG5000-001',
        status=InstrumentStatus.AVAILABLE,
        range_min=125,
        range_max=5000,
        range_unit='m3/h',
        dn_mm=150,
        error_percent=1.5,
        certificate_number='PV-F-5000',
        calibration_due='2027-04-22',
        location='KIP warehouse',
        warehouse_bin='F-06',
    ),
    Instrument(
        id='flow-drgmzl-200-001',
        type=InstrumentType.FLOWMETER,
        name='DRG.MZL DN200',
        manufacturer='MKAIR',
        model='DRG.MZL-200',
        serial_number='DRGMZL200-001',
        status=InstrumentStatus.AVAILABLE,
        range_min=500,
        range_max=10000,
        range_unit='m3/h',
        dn_mm=200,
        error_percent=1.5,
        certificate_number='PV-F-ZL200',
        calibration_due='2027-04-22',
        location='KIP warehouse',
        warehouse_bin='F-07',
    ),
    Instrument(
        id='flow-drgmzl-250-001',
        type=InstrumentType.FLOWMETER,
        name='DRG.MZL DN250',
        manufacturer='MKAIR',
        model='DRG.MZL-250',
        serial_number='DRGMZL250-001',
        status=InstrumentStatus.AVAILABLE,
        range_min=781,
        range_max=15625,
        range_unit='m3/h',
        dn_mm=250,
        error_percent=1.5,
        certificate_number='PV-F-ZL250',
        calibration_due='2027-04-22',
        location='KIP warehouse',
        warehouse_bin='F-08',
    ),
    Instrument(
        id='flow-drgmzl-300-001',
        type=InstrumentType.FLOWMETER,
        name='DRG.MZL DN300',
        manufacturer='MKAIR',
        model='DRG.MZL-300',
        serial_number='DRGMZL300-001',
        status=InstrumentStatus.AVAILABLE,
        range_min=1125,
        range_max=22500,
        range_unit='m3/h',
        dn_mm=300,
        error_percent=1.5,
        certificate_number='PV-F-ZL300',
        calibration_due='2027-04-22',
        location='KIP warehouse',
        warehouse_bin='F-09',
    ),
    Instrument(
        id='flow-drgmzl-400-001',
        type=InstrumentType.FLOWMETER,
        name='DRG.MZL DN400',
        manufacturer='MKAIR',
        model='DRG.MZL-400',
        serial_number='DRGMZL400-001',
        status=InstrumentStatus.AVAILABLE,
        range_min=2000,
        range_max=40000,
        range_unit='m3/h',
        dn_mm=400,
        error_percent=1.5,
        certificate_number='PV-F-ZL400',
        calibration_due='2027-04-22',
        location='KIP warehouse',
        warehouse_bin='F-10',
    ),
    Instrument(
        id='flow-drgmzl-500-001',
        type=InstrumentType.FLOWMETER,
        name='DRG.MZL DN500',
        manufacturer='MKAIR',
        model='DRG.MZL-500',
        serial_number='DRGMZL500-001',
        status=InstrumentStatus.AVAILABLE,
        range_min=3125,
        range_max=62500,
        range_unit='m3/h',
        dn_mm=500,
        error_percent=1.5,
        certificate_number='PV-F-ZL500',
        calibration_due='2027-04-22',
        location='KIP warehouse',
        warehouse_bin='F-11',
    ),
    Instrument(
        id='flow-drgmzl-600-001',
        type=InstrumentType.FLOWMETER,
        name='DRG.MZL DN600',
        manufacturer='MKAIR',
        model='DRG.MZL-600',
        serial_number='DRGMZL600-001',
        status=InstrumentStatus.AVAILABLE,
        range_min=4500,
        range_max=90000,
        range_unit='m3/h',
        dn_mm=600,
        error_percent=1.5,
        certificate_number='PV-F-ZL600',
        calibration_due='2027-04-22',
        location='KIP warehouse',
        warehouse_bin='F-12',
    ),
    Instrument(
        id='flow-drgmzl-800-001',
        type=InstrumentType.FLOWMETER,
        name='DRG.MZL DN800',
        manufacturer='MKAIR',
        model='DRG.MZL-800',
        serial_number='DRGMZL800-001',
        status=InstrumentStatus.AVAILABLE,
        range_min=8000,
        range_max=160000,
        range_unit='m3/h',
        dn_mm=800,
        error_percent=1.5,
        certificate_number='PV-F-ZL800',
        calibration_due='2027-04-22',
        location='KIP warehouse',
        warehouse_bin='F-13',
    ),
    Instrument(
        id='pressure-eja110e-001',
        type=InstrumentType.PRESSURE,
        name='EJA110E',
        manufacturer='Yokogawa',
        model='EJA110E',
        serial_number='P-110E-001',
        status=InstrumentStatus.AVAILABLE,
        range_min=0,
        range_max=2.5,
        range_unit='MPa',
        accuracy_class='0.5',
        error_percent=0.5,
        certificate_number='ПВ-P-001',
        calibration_due='2027-03-10',
        location='ИЛ-1',
    ),
    Instrument(
        id='pressure-rosemount-3051-001',
        type=InstrumentType.PRESSURE,
        name='Rosemount 3051S',
        manufacturer='Emerson',
        model='3051S',
        serial_number='P-3051S-001',
        status=InstrumentStatus.AVAILABLE,
        range_min=0,
        range_max=4.0,
        range_unit='MPa',
        accuracy_class='0.1',
        error_percent=0.1,
        certificate_number='ПВ-P-002',
        calibration_due='2027-06-01',
        location='Склад КИП',
        warehouse_bin='P-07',
        notes='Рекомендуемая замена при превышении δP.',
    ),
    Instrument(
        id='pressure-metran-150-001',
        type=InstrumentType.PRESSURE,
        name='Метран-150',
        manufacturer='Метран',
        model='150',
        serial_number='P-M150-001',
        status=InstrumentStatus.IN_CALIBRATION,
        range_min=0,
        range_max=1.6,
        range_unit='MPa',
        accuracy_class='0.25',
        error_percent=0.25,
        certificate_number='ПВ-P-003',
        calibration_due='2026-12-01',
        location='Поверка',
    ),
    Instrument(
        id='temp-metran-286-001',
        type=InstrumentType.TEMPERATURE,
        name='Метран-286',
        manufacturer='Метран',
        model='286',
        serial_number='T-286-001',
        status=InstrumentStatus.AVAILABLE,
        range_min=-50,
        range_max=50,
        range_unit='C',
        accuracy_class='B',
        error_percent=0.34,
        certificate_number='ПВ-T-001',
        calibration_due='2027-03-10',
        location='ИЛ-1',
    ),
    Instrument(
        id='temp-trm-010-001',
        type=InstrumentType.TEMPERATURE,
        name='ТРМ-010',
        manufacturer='ОВЕН',
        model='ТРМ-010',
        serial_number='T-010-001',
        status=InstrumentStatus.AVAILABLE,
        range_min=-60,
        range_max=80,
        range_unit='C',
        accuracy_class='A',
        error_percent=0.15,
        certificate_number='ПВ-T-002',
        calibration_due='2027-07-15',
        location='Склад КИП',
        warehouse_bin='T-03',
    ),
    Instrument(
        id='computer-spg742-001',
        type=InstrumentType.COMPUTER,
        name='СПГ-742',
        manufacturer='ЛОГИКА',
        model='СПГ-742',
        serial_number='VC-742-001',
        status=InstrumentStatus.AVAILABLE,
        range_unit='PTZ',
        error_percent=0.05,
        certificate_number='ПВ-VC-001',
        calibration_due='2027-04-30',
        location='ИЛ-1',
    ),
    Instrument(
        id='computer-superflow-001',
        type=InstrumentType.COMPUTER,
        name='SuperFlow 21V',
        manufacturer='ABB',
        model='21V',
        serial_number='VC-21V-001',
        status=InstrumentStatus.AVAILABLE,
        range_unit='PTZ',
        error_percent=0.03,
        certificate_number='ПВ-VC-002',
        calibration_due='2027-09-20',
        location='Склад КИП',
        warehouse_bin='VC-02',
    ),
    Instrument(
        id='analyzer-gas-001',
        type=InstrumentType.ANALYZER,
        name='Газовый хроматограф Хроматэк-Кристалл',
        manufacturer='Хроматэк',
        model='Кристалл 5000',
        serial_number='A-GAS-001',
        status=InstrumentStatus.AVAILABLE,
        range_unit='composition',
        error_percent=0.2,
        certificate_number='ПВ-A-001',
        calibration_due='2027-01-25',
        location='Лаборатория',
    ),
]
